import os
import subprocess

env = Environment(ENV = os.environ, tools = ['default', 'mb_install'])

#if not env.GetOption('clean'):
#    call = [
#        'python',
#        os.path.join('../birdwing','parse_enums.py'),
#        '-p',
#        '-c',
#    ]
#    subprocess.check_call(call)

print(os.getcwd())

command = os.path.join(str(Dir("#/")),  "birdwing/parse_enums.py") + ' -p -c'
output_files = [
    'machine_errors.hh',
    'toolhead_errors.hh',
    'machine_errors.py',
    'toolhead_errors.py',
    ]
input_files = [
    'parse_enums.py',
    'machine_errors.json',
    'toolhead_errors.json',
    ]

env.Command(output_files, input_files, command)
env.Install(os.path.join(str(Dir("#/")), 'cpp', 'include', 'bwcoreutils'), "machine_errors.hh")
env.Install(os.path.join(str(Dir("#/")), 'cpp', 'include', 'bwcoreutils'), "toolhead_errors.hh")
env.Install(os.path.join(str(Dir("#/")), 'cpp', 'include', 'bwcoreutils'), "machine_errors_stringify.cc")
env.Install(os.path.join(str(Dir("#/")), 'cpp', 'include', 'bwcoreutils'), "toolhead_errors_stringify.cc")
