import os
import subprocess

env = Environment(ENV = os.environ, tools = ['default', 'mb_install'])

command = ' '.join([File("#/birdwing/parse_enums.py").abspath, '-p', '-c'])
output_files = [
    'obj/machine_errors.hh',
    'obj/toolhead_errors.hh',
    'obj/machine_errors.py',
    'obj/toolhead_errors.py',
    ]
input_files = [
    'parse_enums.py',
    'machine_errors.json',
    'toolhead_errors.json',
    ]

env.Command(output_files, input_files, command)
env.Install(os.path.join(str(Dir("#/")), 'include', 'bwcoreutils'), "obj/machine_errors.hh")
env.Install(os.path.join(str(Dir("#/")), 'include', 'bwcoreutils'), "obj/toolhead_errors.hh")
env.Install(os.path.join(str(Dir("#/")), 'include', 'bwcoreutils'), "obj/machine_errors_stringify.cc")
env.Install(os.path.join(str(Dir("#/")), 'include', 'bwcoreutils'), "obj/toolhead_errors_stringify.cc")

# This is here to prevent "cannot find target 'install'"  errors. 
# There may be a more logical thing to do with this alias 
Alias("install", "obj")
